language: scala
matrix:
  include:
  - jdk: oraclejdk8
    scala: 2.10.6
    env: SBT_COMMAND='ci'
  - jdk: oraclejdk8
    scala: 2.11.11
    env: SBT_COMMAND='ci'
  - jdk: oraclejdk8
    scala: 2.12.3
    env: SBT_COMMAND='ci release'
before_install:
- openssl aes-256-cbc -K $encrypted_f9502b692882_key -iv $encrypted_f9502b692882_iv
  -in project/.gnupg/rings.tar.enc -out project/.gnupg/rings.tar -d
- tar -xvf project/.gnupg/rings.tar -C project/.gnupg/
before_script:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then git checkout -qf $TRAVIS_BRANCH; fi
script:
- sbt ++$TRAVIS_SCALA_VERSION $SBT_COMMAND
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION"
  - "$HOME/.coursier-cache"
after_success:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
env:
  global:
  - secure: o8F3NlwxAYQgf712wlfBP79EKWEbRwmXg0xrS7lJbc+wPdyVeDHHpXXTj5s+G8KMAqmzhjgK/0Bpmk4DKbLGsNFMkZ4TwknGZ7AVAX6mv4HGYn3HbQS9Zcr8rRfSKgLev0dbhbotLldMR4HvnhBENp7Lgd+rLLWbr7NgRpAIMrdPi28otWQMzr93IvsBASJAxPIpJUPNS96WtW8WaIvl86Wx4M5Mngs7rvdwomxf4G0yU0gM7GML1UiNMY1b5TqlK/ATcH1VYTXfVs3N9uVu1+pB/NrN/LwnaYcCGrYacBDO7pudmxUakaBsKmNmPDgIbezlWs7smyGUq8yJizg/yqa8tV1+dwFwQoZV60cw4mEnhyH0gge8ButZDJIqaN03xCo5nxPlbjqw+N7bb3/VrC2W7AEYpzM40ydpMnmbG0FKZ1DxrbYrOVOFDrS9kTW7F1DPwCj/IzWP/nHFe6xCN4OtrskZLZSCISQiKm4HIcdB2Dk3uF0NxPJfi1nwsZPEA471N610j+a5Ezi/i6xuAHO9U1+sIqXXMlauBpZSwJgMN9oOjLhEnNCUQrMTxGsWqWhONeL+m6edYQYPsX2x6y/UtrXwZ25R3zfxDE/ev9ho+I1K2hd5JmMMDkx2NKkeT27RcDFfovWBncX+BOGncDCCkjjW1brzBu0JFIJRfec=
  - secure: XD08/lwbHM8J835fCMGtv60ZGKU/Kt9yrvF7fGEwtHPRVwdHbBu5qMAhNC3Z9IEzskfJpEoiVjaf807HnZRTu0h4VFfIFboNTdaWs7pj/NMEOummGpOOteYyTr9eQ9rGdamADokmFye3fuVoOml0T4vvws3Ilx/DWJhwJVUqAU+UBM//xVUlgNkPW5syYdNIYBSV/MLJPl2w9UOhFYtt2Qzf3cXf0mg631CyMxMZ2yq/shmfDEhBDLkr0pIxZn51Nv5BFMq8Lh/E5ptqkYY9hRFhuioU4qUtK+4fwcZoU3vdtglGud45+2sI5DJBjTHX7lw6buWK9yAvSwZM9jtbayvaY0baNu8tdDdddDYZyLX4BeJEwhsE9YnMylxE15QuSTRQv1SkAkfRTADLNdVtWt8JAYZ/oKVWqtNHCmzh9NshbjhiEbVHBOS9k1er56IpGI6a0PSiYn0m+ScNa1fCbZbPnNOTUc62xPfDk0HhYUnLvmGcKDruzorYqFDBDrPW+0pcY/ZImpkgOtxc0IahWQ87+Td5I6ZQmeNav1VCM1ekHQrzLRrYRqzmWa5WbGo5fVdgLYnq7LFpNnkskCDm1Z198lMncI01GYKpxUOFcBdBwXH9WbqFQIDiBnnte9Hi2UaoLyarcD1xoEzxmgLG1zx8D36ePeqT6zikLJn8tL0=
  # bob
  - secure: pE5NyopICJJS/5WNlqQmKr0TaBe4vNqbs4V+JkPNjYeMbhYkxmkCgvg9vcwcTfQSSbjWMVA5W/kLZcy/tCzf0KGU3ATvGJeMka6zth8NKSmu82DzUktIT4DpgyUzvbfIntIapoEiBfSOeW2WeRUTdQ8GHeUHgFTdxRjxvaX9cFWOFcFO7Szy6UbEzklbC9TBl4Y5A7CDIBjXYrzjisnsFFTQ6LpNQCAFl38joeVugwsQVKfbineF7104Nfw2apTHVtd1lRLvSzmmKGsHUCW58NhVJ4TN51XgbY1lIZkS5t+69uZ/UAMWI/0tEnOK0L/QFlt7oa7oMKYpZSwkPm1ZGjV0McvIF6QfZEdCX70zYlarxAMb1++mRF30QLBSnvDPpBLjdlL08EEew8ZuMRD7MZs4h+Kihs/fwOL7IUjnpBjqJGn3SZe9qudNSRIN9TmzR7CvXqkxBUDV/ePsyvB+Vc+cGuOzhbc4kdorsbN3qZzSTH3W9SLTnoLuvUn8UK9WCseN1dh4oRT+EdW97XB6jksQnOc9ADA6vv97Vi+tTr2tKJOTemjAp67BWlNyloVaPCnymvtx0fY6AXjMhLs5OYhpvp6WLL0jm3y/rrQBLJYXVSVD0hotpdKnkDls9UXUeUI5pdbdnCcNT3AB75IumB3Hs2etECnrWA2f7wCoqgI=
