addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.1.0")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "2.0")
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-RC10")
addSbtPlugin("org.tpolecat" % "tut-plugin" % "0.6.1")
addSbtPlugin("com.lucidchart" % "sbt-scalafmt" % "1.10")